version: "3"
services:
  firefox2:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox2
    security_opt:
      - seccomp=unconfined #opcional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Lisbon #alterado para Lisboa
    volumes:
      - /var/etc/firefox
    ports:
      - "3002:3002"
      - "3003:3003"
    shm_size: "1gb"
    restart: unless-stopped
