version: "3"
services:
  alvaro:
    image: lscr.io/linuxserver/firefox:latest
    container_name: alvaro
    security_opt:
      - seccomp=unconfined #opcional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon #alterado para Lisboa
    volumes:
      - /var/etc/alvaro
    ports:
      - "4000:4000"
      - "4001:4001"
    shm_size: "1gb"
    restart: unless-stopped
