version: "3"
services:
  alvaro:
    image: lscr.io/linuxserver/firefox:latest
    container_name: alvaro
    security_opt:
      - seccomp=unconfined #opcional
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/Lisbon #alterado para Lisboa
    volumes:
      - /var/etc/alvaro
    ports:
      - "3002:3002"
      - "3003:3003"
    shm_size: "1gb"
    restart: unless-stopped
