version: '3'
services:
  dhcp:
    image: networkboot/dhcpd:latest
    container_name: dhcp
    restart: always
    networks:
      - wifi
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
      - /var/lib/dhcp:/var/lib/dhcp
    command: dhcpd -4 -f

networks:
  wifi:
    driver: bridge
